amd64_builder:
  env:
    LINUX_ARCH: amd64
  matrix:
    - env:
      PHP_VERSION: 7.4
    - env:
      PHP_VERSION: 8.0
    - env:
      PHP_VERSION: 8.1
  docker_cache:
    folder: /tmp/.buildx-cache
    fingerprint_key: php-${PHP_VERSION}-${LINUX_ARCH}-key
  setup_script: |
    docker buildx create --name multibuilder
    docker buildx use multibuilder
    docker buildx inspect --bootstrap
  build_script: |
    docker buildx build --platform=linux/amd64,linux/386 \
      -t joseluisq/php-fpm:${PHP_VERSION} \
      --cache-from=type=local,src=/tmp/.buildx-cache \
      --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
      -f ${PHP_VERSION}-fpm/Dockerfile .
  cache_swap_script: |
    rm -rf /tmp/.buildx-cache
    mv /tmp/.buildx-cache-new /tmp/.buildx-cache

arm64_builder:
  env:
    CIRRUS_ARCH: arm64
    LINUX_ARCH: arm64
  matrix:
    - env:
      PHP_VERSION: 7.4
    - env:
      PHP_VERSION: 8.0
    - env:
      PHP_VERSION: 8.1
  docker_cache:
    folder: /tmp/.buildx-cache
    fingerprint_key: php-${PHP_VERSION}-${LINUX_ARCH}-key
  setup_script: |
    docker buildx create --name multibuilder
    docker buildx use multibuilder
    docker buildx inspect --bootstrap
  build_script: |
    docker buildx build --platform=linux/arm64,linux/arm/v6,linux/arm/v7 \
      -t joseluisq/php-fpm:${PHP_VERSION} \
      --cache-from=type=local,src=/tmp/.buildx-cache \
      --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
      -f ${PHP_VERSION}-fpm/Dockerfile .
  cache_swap_script: |
    rm -rf /tmp/.buildx-cache
    mv /tmp/.buildx-cache-new /tmp/.buildx-cache
