task:
  alias: build-linux-image
  timeout_in: 120m
  env:
    DOCKER_USERNAME: ENCRYPTED[a46dbc7bd1e330a9c0f3d85b447f83e57c9858e2e87366b5bfa958b52ee2e51cebdee0a5f70e36fbe3e342b50aadf52a]
    DOCKER_PASSWORD: ENCRYPTED[8d433bb6027eddad4813c84d0d2b694744dd24e6debbfff0078556772454898c9ac8871eb3210f51bb6180e74c0c46c0]
  matrix:
    - name: linux-amd64
      env:
        LINUX_ARCH: amd64
        LINUX_PLATFORM: linux/amd64
      compute_engine_instance:
        image_project: cirrus-images
        image: family/docker-builder
        platform: linux
        cpu: 4
        memory: 4G
    - name: linux-386
      env:
        LINUX_ARCH: 386
        LINUX_PLATFORM: linux/386
      compute_engine_instance:
        image_project: cirrus-images
        image: family/docker-builder
        platform: linux
        cpu: 4
        memory: 4G
    - name: linux-arm64
      env:
        LINUX_ARCH: arm64
        LINUX_PLATFORM: linux/arm64
      compute_engine_instance:
        image_project: cirrus-images
        image: family/docker-builder-arm64
        architecture: arm64
        platform: linux
        cpu: 4
        memory: 4G
    - name: linux-armv6
      env:
        LINUX_ARCH: armv6
        LINUX_PLATFORM: linux/arm/v6
      compute_engine_instance:
        image_project: cirrus-images
        image: family/docker-builder-arm64
        architecture: arm64
        platform: linux
        cpu: 8
        memory: 8G
    - name: linux-armv7
      env:
        LINUX_ARCH: armv7
        LINUX_PLATFORM: linux/arm/v7
      compute_engine_instance:
        image_project: cirrus-images
        image: family/docker-builder-arm64
        architecture: arm64
        platform: linux
        cpu: 8
        memory: 8G
  matrix:
    - env:
        PHP_VERSION: 7.4
    - env:
        PHP_VERSION: 8.0
    - env:
        PHP_VERSION: 8.1
  docker_cache:
    folder: /tmp/.buildx-cache
    fingerprint_key: php-${PHP_VERSION}-${LINUX_ARCH}-key
  setup_script: |
    if [[ "$LINUX_ARCH" = "armv7" ]] || [[ "$LINUX_ARCH" = "armv6" ]]; then
      docker run --privileged --rm tonistiigi/binfmt --install arm
    fi

    docker buildx create --name multibuilder
    docker buildx use multibuilder
    docker buildx inspect --bootstrap
  build_script: |
    docker buildx build \
      --platform=${LINUX_PLATFORM} \
      -t joseluisq/php-fpm:${PHP_VERSION} \
      --cache-from=type=local,src=/tmp/.buildx-cache \
      --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
      -f ${PHP_VERSION}-fpm/Dockerfile .
  tag_script: |
    if [[ -z "$CIRRUS_TAG" ]]; then echo "Script skipped!"
    else
      docker tag joseluisq/php-fpm:${PHP_VERSION} joseluisq/php-fpm:$PHP_VERSION-$LINUX_ARCH
    fi
  login_script: |
    if [[ -z "$CIRRUS_TAG" ]]; then echo "Script skipped!"
    else
      docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
    fi
  push_script: |
    if [[ -z "$CIRRUS_TAG" ]]; then echo "Script skipped!"
    else
      docker push joseluisq/php-fpm:$PHP_VERSION-$LINUX_ARCH
    fi
  cache_swap_script: |
      rm -rf /tmp/.buildx-cache
      mv /tmp/.buildx-cache-new /tmp/.buildx-cache

release_docker_builder:
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - build-linux-image
  env:
    DOCKER_USERNAME: ENCRYPTED[a46dbc7bd1e330a9c0f3d85b447f83e57c9858e2e87366b5bfa958b52ee2e51cebdee0a5f70e36fbe3e342b50aadf52a]
    DOCKER_PASSWORD: ENCRYPTED[8d433bb6027eddad4813c84d0d2b694744dd24e6debbfff0078556772454898c9ac8871eb3210f51bb6180e74c0c46c0]
    PHP_LATEST_VERSION: 8.1
  matrix:
    - env:
        PHP_VERSION: 7.4
    - env:
        PHP_VERSION: 8.0
    - env:
        PHP_VERSION: ${PHP_LATEST_VERSION}
  login_script: |
    docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_latest_per_version_script: |
    docker manifest create \
      joseluisq/php-fpm:$PHP_VERSION \
        --amend joseluisq/php-fpm:$PHP_VERSION-amd64 \
        --amend joseluisq/php-fpm:$PHP_VERSION-386 \
        --amend joseluisq/php-fpm:$PHP_VERSION-arm64 \
        --amend joseluisq/php-fpm:$PHP_VERSION-armv6 \
        --amend joseluisq/php-fpm:$PHP_VERSION-armv7
    docker manifest push joseluisq/php-fpm:$PHP_VERSION
  push_latest_script: |
    if [[ "$PHP_VERSION" = "$PHP_LATEST_VERSION" ]]; then
      docker manifest create \
        joseluisq/php-fpm:latest \
          --amend joseluisq/php-fpm:$PHP_VERSION-amd64 \
          --amend joseluisq/php-fpm:$PHP_VERSION-386 \
          --amend joseluisq/php-fpm:$PHP_VERSION-arm64 \
          --amend joseluisq/php-fpm:$PHP_VERSION-armv6 \
          --amend joseluisq/php-fpm:$PHP_VERSION-armv7
      docker manifest push joseluisq/php-fpm:latest
    else
      echo "Script skipped!"
    fi
  pull_latest_script: |
    docker pull joseluisq/php-fpm:$PHP_VERSION-amd64
    docker pull joseluisq/php-fpm:$PHP_VERSION-386
    docker pull joseluisq/php-fpm:$PHP_VERSION-arm64
    docker pull joseluisq/php-fpm:$PHP_VERSION-armv6
    docker pull joseluisq/php-fpm:$PHP_VERSION-armv7
  semver_aliases_script: |
    SEMVER=${CIRRUS_TAG##*v}
    echo "SEMVER=${SEMVER}" >> $CIRRUS_ENV
    echo "SEMVER_MAJOR=${SEMVER%.*.*}" >> $CIRRUS_ENV
    echo "SEMVER_MINOR=${SEMVER%.*}" >> $CIRRUS_ENV
  push_semver_alias_script: |
    docker manifest create \
      joseluisq/php-fpm:${SEMVER} \
        --amend joseluisq/php-fpm:$PHP_VERSION-amd64 \
        --amend joseluisq/php-fpm:$PHP_VERSION-386 \
        --amend joseluisq/php-fpm:$PHP_VERSION-arm64 \
        --amend joseluisq/php-fpm:$PHP_VERSION-armv6 \
        --amend joseluisq/php-fpm:$PHP_VERSION-armv7
    docker manifest push joseluisq/php-fpm:${SEMVER}
  push_semver_major_alias_script: |
    docker manifest create \
      joseluisq/php-fpm:${SEMVER_MAJOR} \
        --amend joseluisq/php-fpm:$PHP_VERSION-amd64 \
        --amend joseluisq/php-fpm:$PHP_VERSION-386 \
        --amend joseluisq/php-fpm:$PHP_VERSION-arm64 \
        --amend joseluisq/php-fpm:$PHP_VERSION-armv6 \
        --amend joseluisq/php-fpm:$PHP_VERSION-armv7
    docker manifest push joseluisq/php-fpm:${SEMVER_MAJOR}
  push_semver_minor_alias_script: |
    docker manifest create \
      joseluisq/php-fpm:${SEMVER_MINOR} \
        --amend joseluisq/php-fpm:$PHP_VERSION-amd64 \
        --amend joseluisq/php-fpm:$PHP_VERSION-386 \
        --amend joseluisq/php-fpm:$PHP_VERSION-arm64 \
        --amend joseluisq/php-fpm:$PHP_VERSION-armv6 \
        --amend joseluisq/php-fpm:$PHP_VERSION-armv7
    docker manifest push joseluisq/php-fpm:${SEMVER_MINOR}
