name: devel-8.3
on:
  pull_request:
    branches:
      - master
    paths:
      - 8.3-fpm/**
      - .github/workflows/devel-8.3.yml
  push:
    branches:
      - master
    paths:
      - 8.3-fpm/**
      - .github/workflows/devel-8.3.yml

jobs:
  php:
    strategy:
      matrix:
        build:
          - amd64
          - "386"
          - arm64
          - armv7
          - armv6
        include:
          - build: amd64
            arch: linux/amd64
            os: ubuntu-22.04
          - build: "386"
            arch: linux/386
            os: ubuntu-22.04
          - build: arm64
            arch: linux/arm64
            os: ubuntu-22.04-arm
          - build: armv6
            arch: linux/arm/v6
            os: ubuntu-22.04-arm
          - build: armv7
            arch: linux/arm/v7
            os: ubuntu-22.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      -
        name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: 8.3-fpm-${{ matrix.arch }}-buildx-${{ hashFiles('8.3-fpm/**') }}
          restore-keys: |
            8.3-fpm-${{ matrix.arch }}-buildx-${{ hashFiles('8.3-fpm/**') }}
            8.3-fpm-${{ matrix.arch }}-buildx-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and Test
        uses: docker/build-push-action@v6
        with:
          push: false
          provenance: false
          context: .
          platforms: ${{ matrix.arch }}
          file: 8.3-fpm/Dockerfile
          tags: joseluisq/php-fpm:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
